name: Java CI with Selenium

on: [push, pull_request]

jobs:
  build:
    runs-on: THANUJAJAYAPRAK

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Selenium Tests
      run: mvn clean test
